Pacify gcc 10.3.0 on false null pointer warning
Enabling UBSAN caused the analyzer to warn

  src/ddsrt/src/avl.c: In function ‘ddsrt_avl_insert’:
  src/ddsrt/src/avl.c:419:5: error: use of NULL ‘vnode’ where non-null
    expected [CWE-690] [-Werror=analyzer-null-argument]

this is nonsense, possibly caused by a null pointer check in
cnode_from_onode().

This commit adds a few conversion functions that omit the null pointer
check and are annotated as requiring a non-null pointer and uses them
where applicable.  Various non-null annotations got added as well.

Signed-off-by: Erik Boasson <eb@ilities.com>