Rename sched_priority for CentOS 7 compatibility
The error that's breaking the build is this:

ddsi_cfgelems.h:688:54: error: 'struct ddsi_config_thread_properties_listelem'
has no member named '__sched_priority'; did you mean 'sched_priority'?
     MEMBEROF(ddsi_config_thread_properties_listelem, sched_priority),
                                                      ^~~~~~~~~~~~~~
which thanks to some spelunking by @clalancette we've found is due to the fact
that on CentOS 7, the /usr/include/sched.h file provided by the
glibc-headers-2.17-307.el7.1.x86_64 package includes the following on line 44:

Thanks @clanlancette and @nuclearsandwich!

Signed-off-by: Erik Boasson <eb@ilities.com>